name: Test

on: [pull_request]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
